### ISSUE TITLE
Problem pages

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/iver-wharf.github.io#23]
We're introducing problem types, according to [IETF RFC-7087](https://www.rfc-archive.org/getrfc?rfc=7807#gsc.tab=0), and need problem describing pages for the following:

- [x] docs/prob/api/internal-server-error.md (#27)
- [ ] docs/prob/api/invalid-param.md
- [x] docs/prob/api/invalid-param-int.md (#27)
- [x] docs/prob/api/invalid-param-uint.md (#27)
- [ ] docs/prob/api/missing-param-string.md
- [ ] docs/prob/api/project/cannot-change-group.md
- [ ] docs/prob/api/project/run/params-deserialize.md
- [ ] docs/prob/api/project/run/params-serialize.md
- [ ] docs/prob/api/project/run/trigger.md
- [ ] docs/prob/api/provider/invalid-name.md
- [ ] docs/prob/api/record-not-found.md
- [ ] docs/prob/api/unexpected-body-read-error.md
- [ ] docs/prob/api/unexpected-db-read-error.md
- [ ] docs/prob/api/unexpected-db-write-error.md
- [ ] docs/prob/api/unexpected-multipart-read-error.md
- [ ] docs/prob/build/run/invalid-input.md

See api!45 and api!46 MRs for more info (sorry, not open sourced yet)
