### ISSUE TITLE
Move remaining repos

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/iver-wharf.github.io#32]
Remaining repos:

- [x] helm chart (iver-wharf/wharf-helm#1)
- [x] cmd repo (iver-wharf/wharf-cmd#1)
- [x] architecture notes repo (iver-wharf/wharf-notes#1)

Rules for moving these:

- Redact all company references
- No Git history. Safest way is just copying all files except the `.git` folder into the new repo

Once these has been moved we can update the "About Wharf" page in this repo so it no longer says "goal is to be open sourced by end of 2021"
